# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '8.4'

target 'app' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for app
	pod 'Bolts'
	pod 'FBSDKCoreKit'
	pod 'FBSDKLoginKit'
	pod 'Firebase', '~> 2.5.1'
	pod 'Parse'
	pod 'ParseFacebookUtilsV4'
	pod 'ParseTwitterUtils'

	pod 'AFNetworking', '~> 2.6.3'
	pod 'IQAudioRecorderController'
	pod 'MBProgressHUD'
	pod 'ProgressHUD'
	pod 'RNGridMenu'
	pod 'SDWebImage'

end
